networks:
    soketi-network:
        name: soketi-app-manager-network
        driver: bridge

services:
    soketi-app-manager:
        build:
            context: ./docker
            dockerfile: Dockerfile
        image: soketi-app-manager
        container_name: soketi-app-manager
        depends_on:
            mysql:
                condition: service_healthy # Important for auto database migration
        volumes:
            - '.:/var/www/html'
        networks:
            - soketi-network
    
    nginx:
        image: 'nginx:stable-alpine3.17-slim'
        container_name: soketi-app-manager-nginx
        depends_on:
            - soketi-app-manager
            - soketi
        volumes:
          - './docker/nginx.conf:/etc/nginx/conf.d/default.conf'
          - '.:/var/www/html'
        ports:
          - '${APP_PORT:-80}:80'
        networks:
            - soketi-network

    mysql:
        image: 'mysql/mysql-server:8.0'
        container_name: soketi-app-manager-mysql
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - './docker/data/mysql:/var/lib/mysql'
        networks:
            - soketi-network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-u", "${DB_USERNAME}", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
            interval: 5s

    redis:
        image: 'redis:7.2-alpine'
        container_name: soketi-app-manager-redis
        command: redis-server --save 60 1 --loglevel warning --requirepass "${REDIS_PASSWORD}"
        volumes:
            - './docker/data/redis:/data'
        networks:
            - soketi-network

    soketi:
        image: 'quay.io/soketi/soketi:latest-16-alpine'
        container_name: soketi-websocket-server
        depends_on:
            - mysql
            - redis
        volumes:
            - './.env:/app/.env'
        networks:
            - soketi-network
